name: EX/VO
# url: https://skailasa.github.io/
# baseurl: "exvo"
# title: "EX/VO Blog"
description: "Surf the cyberweb"
permalink: "/:year/:month/:day/:title/"
markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
author: "The Dictator"
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
