name: EX/VO
title: "EX/VO"                 # optional but many plugins expect 'title'
url: "https://exhibitionismvoyeurism.github.io"
baseurl: " "
description: "Surf the cyberweb"

permalink: "/:year/:month/:day/:title/"
markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author: "The Dictator"

collections:
  announcements:
    output: true
    permalink: /announcements/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
  - scope:
      path: ""
      type: announcements
    values:
      layout: post         # or make a custom 'announcement' layout
      comments: false
